// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzmpuojqcrrlylmnbgrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6bXB1b2pxY3JybHlsbW5iZ3JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MzM2NzYsImV4cCI6MjA2NzMwOTY3Nn0.RD0ZY4QEhugee4hKoKyEIOAglcqyVi-D9ZabFAK5f8o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});